-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE CATEGORIES(CODE VARCHAR(15) primary key,
                        NAME VARCHAR(100) unique not null,
                        DESCRIPTION VARCHAR(300) not null,
                        ACTIVE BOOLEAN);

-- changeset liquibase:3
CREATE TABLE COMPANIES(ID BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
                       NAME VARCHAR(50) NOT NULL,
                       DESCRIPTION VARCHAR(200) NOT NULL,
                       TAX_NUMBER VARCHAR(20) NOT NULL UNIQUE,
                       PHONE BIGINT NOT NULL,
                       ACTIVE BOOLEAN,
                       REGISTER_DATE DATE,
                       REMOVE_DATE DATE);

CREATE TABLE DONEES(ID BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
                    COMPANY_ID BIGINT NOT NULL,
                    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID));

-- changeset liquibase:4
CREATE TABLE PERSONS(ID INT primary key,
                    FIRST_NAME VARCHAR(50) not null,
                    LAST_NAME VARCHAR(50) not null,
                    NIF VARCHAR(20) unique not null,
                    ADDRESS VARCHAR(150) not null,
                    EMAIL VARCHAR(100) unique not null,
                    PASSWORD VARCHAR(50) not null);

CREATE TABLE DONORS(ID BIGINT primary key,
                    PERSON_ID BIGINT NOT NULL,
                    FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(ID));

-- changeset liquibase:5
ALTER TABLE DONEES ADD COLUMN PASSWORD VARCHAR(20) NOT NULL;
ALTER TABLE DONEES ADD COLUMN ACTIVE BOOLEAN NOT NULL;

-- changeset liquibase:6
CREATE TABLE DONEES_CATEGORIES(DONEE_ID BIGINT NOT NULL,
                               CATEGORY_CODE VARCHAR(15) NOT NULL,
                               FOREIGN KEY (DONEE_ID) REFERENCES DONEES(ID),
                               FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE),
                               PRIMARY KEY (DONEE_ID, CATEGORY_CODE));

-- changeset liquibase:7
CREATE TABLE DONATIONS(ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       TITLE VARCHAR(50) NOT NULL,
                       DESCRIPTION VARCHAR(500) NOT NULL,
                       CREATED_DATE TIMESTAMP NOT NULL,
                       ACTIVE BOOLEAN NOT NULL);

CREATE TABLE DONATIONS_CATEGORIES(DONATION_ID BIGINT NOT NULL,
                                  CATEGORY_CODE VARCHAR(15) NOT NULL,
                                  FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID),
                                  FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE),
                                  PRIMARY KEY(DONATION_ID, CATEGORY_CODE));

-- changeset liquibase:8
CREATE TABLE DONATION_IMAGES(ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ORIGINAL_NAME VARCHAR(100) NOT NULL,
                             FILE_NAME VARCHAR(100) NOT NULL,
                             DIRECTORY_PATH VARCHAR(300) NOT NULL,
                             FILE_EXTENSION VARCHAR(100) NOT NULL,
                             FILE_SIZE NUMERIC NOT NULL,
                             DONATION_ID BIGINT NOT NULL,
                             ACTIVE BOOLEAN NOT NULL,
                             FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID));

CREATE TABLE DONATIONS_PROCESS(ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              DONATION_ID BIGINT NOT NULL,
                              STATUS VARCHAR(10) NOT NULL,
                              DONEE_ID BIGINT,
                              FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID),
                              FOREIGN KEY (DONEE_ID) REFERENCES DONEES(ID))